### ISSUE TITLE
Support for Namespaces

### ISSUE THREAD

**Issue by ncresswell** [portainer/k2d#13]
In the alpha, we emulate just a single namespace, the "default" namespace, and all resources deployed in this namespace are attached to the docker network k2d_net.

We could provide emulated namespaces, by mapping namespace creation to the creation of a custom docker bridge network, and then using the namespace name to map to the appropriate docker network.

**Comment by deviantony** [comment]
Partial namespace support has been introduced via #30 

We're still missing namespace support for ConfigMap and Secret resources.
