### ISSUE TITLE
Refactor Secrets and ConfigMaps to Docker Volumes

### ISSUE THREAD

**Issue by stevensbkang** [portainer/k2d#20]
It will be good to migrate secrets and configMaps stored in the filesystem to Docker volumes. It will have the following advantages:

- Bind mount for `/var/lib/k2d` will not be required anymore. Instead, the use of a Docker volume will then be possible to store TLS and token data for `k2d`.
- No need for maintaining metadata files to store annotations and labels. Rather, these can be pushed to Docker Volume labels which will be cleaner.
- Can be expanded to support PV/PVC by the Docker volume support.

**Comment by deviantony** [comment]
Based on @stevensbkang original idea and implementations in #2  and #26, the implementation has been added via https://github.com/portainer/k2d/pull/31

See the PR for more info about the implementation.
