### ISSUE TITLE
Support extra column output with -o wide

### ISSUE THREAD

**Issue by rothgar** [portainer/k2d#86]
Kubectl typically has different output output options and it looks like some of them like `-o json` are supported (this is probably client side) but other's like `-o wide` are not supported.

This would be helpful for getting more information from pods, services, etc. Not all of the columns are useful on a single node but it would still be nice to have.

**Comment by deviantony** [comment]
I think that we can start with wide format for pods, nodes, deployments and services. Any other resource that you think would be interesting to support?
